import type { Metadata } from "next";
import PayPalProvider from "@/_components/PayPalProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PayPalProvider>{children}</PayPalProvider>
      </body>
    </html>
  );
}
